### PR TITLE
Port website build over to Hugo

### PR DESCRIPTION
**Pull request by jhenstridge**
This is a massively incomplete port of the website from Jekyll to [Hugo](https://gohugo.io/).  So far, I've only attacked the following parts of the site:

1. The template layouts plus CSS.
2. The home page
3. The committee minutes (since this is the one part of the current site where we were using collections of posts).

Porting the rest of the site would mostly just mean moving them to the `content/` or `static/` tree.  Like Jekyll, pages are markdown with YAML front matter.  So if the page doesn't use any special Jekyll template code, it shouldn't need any changes.

With Hugo installed, the branch can be tested by running `hugo server` and pointing your browser at http://localhost:1313/.  Running `hugo` on its own will build the site, ready to deploy.

### CODE REVIEW

**Comment by Zorlin** [comment]
We'd have to fully commit (no pun intended) to Hugo to merge this.

I appreciate the effort! I'm curious as to what prompted this initiative, though I personally use and in fact prefer Hugo.

**Comment by jhenstridge** [comment]
The "why now?" is that I had some time to experiment on the weekend.

The main reasons I had for trying this were:

1. Jekyll seems to be mostly designed to manage a single blog plus a few associated static pages.  When adding the committee minutes to the site, I tried to do it in a way that could still allow other date sorted collections of pages but it ended up with a bunch of template code in the markdown pages to generate a the listing.  In contrast, Hugo makes it easy to manage multiple independent collections of pages, which we could use to automatically create lists of AGM minutes and possibly even summaries of our meetings (with video embeds where we have them).

2. We haven't had much luck getting the Jekyll based website published reliably.  A static linked Go binary might be easier to handle.  There are also Docker images available that might simplify deployment while we're still stuck on old Debian.

3. If we can get rid of the templating in the markdown files, then we could also investigate switching to a different theme.  I think the main thing we'd want out of this is something that would render better on mobile.  Of course, we might be able to handle that by extending the current templates though.

I published this as a draft PR, since it is obviously not appropriate to merge as is.  It breaks the Jekyll build, and doesn't complete the port to Hugo.  My reason for publishing it was more to see if there is interest in completing the port.

**Comment by Zorlin** [comment]
Definitely interested

**Comment by jhenstridge** [comment]
The port is a bit more complete now.  I've tried to force the URL of as few pages as possible, and make use of `{{< ref "..." >}}` to form links where possible (which has the benefit of telling us if a link is broken).

There are a number of references to a `/media` folder that doesn't exist in the Jekyll site.  If the content of that folder isn't too big, I wonder if it would make sense to just add them to the git repo?

**Comment by Zorlin** [comment]
Adding huge binary blobs to Git makes Git a sad panda. I think there's about 120MiB of media.

**Comment by jhenstridge** [comment]
These were the only `/media/` links I could see in the site:

http://plug.org.au/media/pictures/01-plug_basic_sml.png
http://plug.org.au/media/pictures/04-plug_networking_sml.png
http://plug.org.au/media/pictures/06-plug_web_sml.png
http://plug.org.au/media/pictures/plug-logo-1-jason.png
http://plug.org.au/media/pictures/plug-logo-2-v1.png
http://plug.org.au/media/pictures/NBNTalk.png
http://plug.org.au/media/pictures/NBNTalk.xcf
http://plug.org.au/media/pictures/QuizNightFlyer_March_20110328.jpg

The last one seems to be broken, but the others total about 3.3MB, with about half that being the XCF file (an uncompressed image format).  That doesn't seem like a huge amount of data to deal with.  If there is other stuff in the `/media/` directory, it isn't referenced from anywhere else on the website.

I'm definitely not suggesting we include video in the repository, which is referenced as `/videos/` URLs.

**Comment by Zorlin** [comment]
Oh, 3.3MiB is fine. I withdraw my objections.
- w

**Comment by jhenstridge** [comment]
I discussed files in /media/ with Nick on IRC, and I don't think it is worth pursuing with this branch.  The unlinked content in that folder probably represents stuff we should make reachable on the website, and brings us to the tens of megabytes range.

I think this conversion is mostly complete now.  I've turned on unsafe markup to fix the calendar embed, and moved the yearly  event archives back to their current URLs.

I'm going to try and set up a Github Actions workflow that will build the site to the gh-pages branch, which would let us keep the plugorgau.github.io staging site available.  If I get that working, it could potentially be used to roll out the production site without having to build it on our server (i.e. just check out the gh-pages branch rather than master).

**Comment by jhenstridge** [comment]
Once we decide to make this move, there are a few other changes I'd like to make:

1. split the event data into one markdown file per event, and generate the yearly archives automatically.
2. add our recent events to the site
3. add YouTube embeds to events where we recorded the talk
4. see if we can generate an iCalendar file from event data

The last one is mostly an experiment, but might offer a way to manage upcoming events on the website itself.

**Comment by jhenstridge** [comment]
Another small simplification: through the use of a `render-link.html` template, we can enable direct links between markdown files, converting them to the path of the corresponding page when rendered to HTML.  This gets rid of all the Hugo shortcode use currently found in the content/ directory.

**Comment by jhenstridge** [comment]
I've updated the branch to add a Github Actions workflow that pushes a built version of the website to [the gh-pages branch](https://github.com/plugorgau/plugorgau.github.io/tree/gh-pages) of this repository.  At the moment, it runs on pushes to the hugo-port branch, but this should be changed to master when this PR is merged.

The main benefits of this are:
1. We can continue to use plugorgau.github.io as a staging version of the website.
2. We get some feedback on whether the website build is working or not through the check result.
3. We have the option of directly deploying the gh-pages branch to www.plug.org.au, as an alternative to trying to install new software on the old distro release we're running.

**Pull request merged**
